SCREEN_WIDTH = 750
SCREEN_HEIGHT = 500

ENEMY_MIN_SIZE = 10
ENEMY_SIZES = 4
ENEMY_BASE_SPEED = 40
ENEMY_MAX_SIZE = ENEMY_SIZES * ENEMY_MIN_SIZE
ENEMY_SPAWN_MIN = 3
ENEMY_SPAWN_MAX = 10
ENEMY_MELEE_SIZE = 20

PLAYER_BASE_SPEED = 50

SHOT_BASE_RANGE = 100
SHOT_RADIUS = 2
PLAYER_SHOOT_SPEED = 500

MELEE_BASE_SIZE = 25
MELEE_SWIPE_RATE = 1

ITEMS_PER_PAGE = 8
